### ISSUE TITLE
DllNotFoundException

### ISSUE THREAD

**Issue by keesschollaart81** [entrepreneur-interet-general/H3.Standard#1]
Hi,

I'm trying the 3.2.0 version of your package and it's giving me a System.DllNotFoundException

Steps to reproduce:
```dotnet new console```
```dotnet add package H3```
in the Main method:
```csharp
using System;
using H3Standard;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            var h3 = H3.GeoToH3(51.9914692, 5.0760207, 5);

            Console.WriteLine("Hello World!");
        }
    }
}

```
```dotnet build```  > Compiles succesfully
```dotnet run``` > results in:
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'h3lib.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at H3Standard.H3.geoToH3(H3GeoCoord& g, Int32 res)
   at H3Standard.H3.GeoToH3(Double latitude, Double longitude, Int32 resolution)
   at test.Program.Main(String[] args) in C:\projects\test\Program.cs:line 10
```
This is the same if I change the TargetFramework from netcoreapp2.1 to net472

My ```dotnet --info``` is 
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.400
 Commit:    8642e60a0f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

Update: I also tried it on a MacBook with the following ```dotnet --info``` but this gives the same error:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  1.0.0-preview1-002697 [/usr/local/share/dotnet/sdk]
  1.0.0-preview2-003148 [/usr/local/share/dotnet/sdk]
  1.0.0-preview2-1-003177 [/usr/local/share/dotnet/sdk]
  1.0.4 [/usr/local/share/dotnet/sdk]
  2.0.0-preview1-005977 [/usr/local/share/dotnet/sdk]
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0-rc2-3002697 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0-preview1-002111-00 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by TheSpy** [comment]
Hey, you need to call H3.InstanciateNativeLibrary(); to get dll copied to the output folder before calling GeoToH3

**Comment by keesschollaart81** [comment]
Cool, I'm not able any more to try it out but I'm sure the next one reading this will appreciate your reply/solution! 👍

**Comment by ArnaudSwail** [comment]
Hi, thanks every one to point on this awkward way of managing nuget distribution of this package.

After a battle of a few days, using nuget reference docs and [stackoverflow](https://stackoverflow.com/questions/19478775/add-native-files-from-nuget-package-to-project-output-directory) , I found that the embedded resource proposed by Ondrej Janacek was the only one working with nuget in a single pack. The dll is oversized with the native dll as a resource, and you have to call H3.InstanciateNativeLibrary() once (and never in prod and so on...). 

After browsing of a few better packed groups of managed and dynamic library, it seems that the clean way to go is to create two separate packages, one for managed libraries and one for native ones, which seems fair after all...

Uber core library is updating quite often these days, I'll pack a new version in the next weeks.

**Comment by wJohnwarne** [comment]
Hi,

The above mentioned issue is what I currently face. I have tried the above suggested solution with unfortunate results. Any assistance would be greatly appreciated?

I have provided the same information below:
```
        public ulong Test()
        {
            GeoCoord location;
            location.latitude = H3.RadToDeg(40.689167);
            location.longitude = H3.RadToDeg(-74.044444);
            var resolution = 10;
            H3.InstanciateNativeLibrary();
            return H3.GeoToH3(location.latitude, location.longitude, resolution);
        }
```
```
 System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)'
```
```
 .NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App] 
```

**Comment by ArnaudSwail** [comment]
Best would be to compile the most up-to-date H3 lib, fork this repo and recompile the H3Standard csproj against it. This project is almost 2 years old with a wrapping on Uber H3 3.2.0, a lot of improvements since.

**Comment by tomercagan** [comment]
Hi,
I am also trying to work with the library. In my case I am using .NET Core and I want/plan to run my application in docker.

How should I go about doing it? Do I need to recompile H3Standard within the container? Can I just build and install h3 globaly and use H3Standard a dll from nuget?

Thanks

**Comment by jazarforcite** [comment]
Has anyone found a solution to this? i'm trying to integrate the H3 Library with a .NET core api application to no avail, even though it's working properly on a desktop application with the same nuget package. I also tried adding the 3.2.0-rc version which did not work either. Can someone advise on how to fix this issue?
